- id: '1'
  alias: Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    service: ifttt.trigger
    data:
      event: HA_Startup
      value1: Home Assistant Startup

- id: '1504843384907'
  alias: Activate Living Room Hue Scene
  trigger:
    platform: state
    entity_id: input_select.living_room_mood
    from: Select Mood
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Living Room
      scene_name: '{{ trigger.to_state.state }}'
  - service: input_select.select_option
    entity_id: input_select.living_room_mood
    data_template:
      option: Select Mood

- id: '1504850140660'
  alias: Activate Bedroom Hue Scene
  trigger:
    platform: state
    entity_id: input_select.bedroom_mood
    from: Select Mood
  action:
  - service: light.hue_activate_scene
    data_template:
      group_name: Bedroom
      scene_name: '{{ trigger.to_state.state }}'
  - service: input_select.select_option
    entity_id: input_select.bedroom_mood
    data_template:
      option: Select Mood
