homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
      hide_control: false

    "light.*":
      custom_ui_state_card: state-card-custom-ui
      hide_control: false
      state_card_mode: single-line
      stretch_slider: true


# Customization file
  customize: !include customize.yaml

  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
  extra_html_url_es5:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-es5.html

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret hass_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_priv_key
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

recorder:
  db_url: !secret db_url

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Nest Thermostat
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# ifttt Config
ifttt:
  key: !secret ifttt_key

# Included components
automation: !include automations.yaml
camera: !include cameras.yaml
device_tracker: !include device_tracker.yaml
binary_sensor: !include binary_sensors.yaml
input_select: !include input_selects.yaml
#input_slider: !include input_sliders.yaml
light: !include lights.yaml
group: !include groups.yaml
media_player: !include media_players.yaml
mqtt: !include mqtt.yaml
notify: !include notifications.yaml
panel_iframe: !include panel_iframes.yaml
remote: !include remotes.yaml
scene: !include_dir_list scenes
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
