- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - dewpoint_string
    - feelslike_f
    - feelslike_string
    - heat_index_f
    - heat_index_string
    - elevation
    - location
    - observation_time
    - precip_1hr_in
    - precip_1hr_metric
    - precip_1hr_string
    - precip_today_in
    - precip_today_metric
    - precip_today_string
    - precip_1d
    - pressure_in
    - pressure_mb
    - pressure_trend
    - relative_humidity
    - station_id
    - solarradiation
    - temperature_string
    - temp_f
    - temp_high_record_f
    - temp_low_record_f
    - temp_high_1d_f
    - temp_low_1d_f
    - temp_high_2d_f
    - temp_low_2d_f
    - temp_high_3d_f
    - temp_low_3d_f
    - temp_high_4d_f
    - temp_low_4d_f
    - UV
    - visibility_mi
    - weather
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_3d
    - weather_4d
    - wind_degrees
    - wind_dir
    - wind_gust_mph
    - wind_mph
    - wind_string