#---------------------------------------------------------------------------------------------

input_select:
  harmony:
    name: Harmony Control
    icon: mdi:theater
    options:
      - Select Activity
      - Watch Kodi
      - Watch Netflix
      - Watch YouTube
      - Watch TV
      - Play Xbox One
      - Play Xbox 360

  harmony_power:
    name: Device Power
    icon: mdi:power
    options:
      - Select Device
      - Living Room TV
      - Living Room Speakers
      - Android TV
      - Fios DVR
      - Xbox One
      - Xbox 360

  harmony_tv_input:
    name: TV Input
    icon: mdi:television
    options:
      - Select Input
      - TV
      - Xbox
      - Kodi
      - PC

sensor:
  - platform: template
    sensors:
      current_activity:
        friendly_name: 'Current Activity'
        value_template: '{{ states.remote.living_room.attributes.current_activity }}'

#---------------------------------------------------------------------------------------------

group:
  harmony:
    name: Entertainment
    view: no
    entities:
      - remote.living_room
      - sensor.current_activity
      - input_select.harmony
      - input_select.harmony_power
      - input_select.harmony_tv_input
      - script.living_room_amp_volume_up
      - script.living_room_amp_volume_down
      - script.living_room_amp_mute
      - script.living_room_kodi_volume_up
      - script.living_room_kodi_volume_down
      - script.living_room_kodi_mute

#---------------------------------------------------------------------------------------------

script:
  living_room_amp_volume_up:
    sequence:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: 46085817
          command: "VolumeUp"

  living_room_amp_volume_down:
    sequence:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: 46085817
          command: "VolumeDown"

  living_room_amp_mute:
    sequence:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: 46085817
          command: "Mute"

  living_room_kodi_volume_up:
    sequence:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: 46085820
          command: "VolumeUp"

  living_room_kodi_volume_down:
    sequence:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: 46085820
          command: "VolumeDown"

  living_room_kodi_mute:
    sequence:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: 46085820
          command: "Mute"

#---------------------------------------------------------------------------------------------

automation:
  - alias: Harmony Activity
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony
      from: 'Select Activity'

    action:
      - service: remote.turn_on
        entity_id: remote.living_room
        data_template:
          activity: >
            {% if is_state("input_select.harmony", "Watch Kodi") %}
              27328018
            {% elif is_state("input_select.harmony", "Watch Netflix") %}
              27328946
            {% elif is_state("input_select.harmony", "Watch YouTube") %}
              27329162
            {% elif is_state("input_select.harmony", "Watch TV") %}
              27326898
            {% elif is_state("input_select.harmony", "Play Xbox One") %}
              27326936
            {% elif is_state("input_select.harmony", "Play Xbox 360") %}
              27326976
            {% else %}
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Activity"

#---------------------------------------------------------------------------------------------

  - alias: Living Room Harmony Power Toggle
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony_power
      from: 'Select Device'
    action:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: >
            {% if is_state("input_select.harmony_power", "Living Room TV") %}
              46085815
            {% elif is_state("input_select.harmony_power", "Living Room Speakers") %}
              46085817
            {% elif is_state("input_select.harmony_power", "Android TV") %}
              46085820
            {% elif is_state("input_select.harmony_power", "Fios DVR") %}
              46085818
            {% elif is_state("input_select.harmony_power", "Xbox One") %}
              46085814
            {% elif is_state("input_select.harmony_power", "Xbox 360") %}
              46085819
            {% else %}
            {% endif %}
          command: "PowerToggle"
      - service: input_select.select_option
        entity_id: input_select.harmony_power
        data_template:
          option: "Select Device"

#---------------------------------------------------------------------------------------------

  - alias: Living Room TV Input Select
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.harmony_tv_input
      from: 'Select Input'
    action:
      - service: remote.send_command
        entity_id: remote.living_room
        data_template:
          device: 46085815
          command: >
            {% if is_state("input_select.harmony_tv_input", "TV") %}
              InputHdmi1
            {% elif is_state("input_select.harmony_tv_input", "Xbox") %}
              InputHdmi2
            {% elif is_state("input_select.harmony_tv_input", "Kodi") %}
              InputHdmi3
            {% elif is_state("input_select.harmony_tv_input", "PC") %}
              InputHdmi4
            {% else %}
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.harmony_tv_input
        data_template:
          option: "Select Input"

#---------------------------------------------------------------------------------------------


  - alias: Harmony Off
    hide_entity: True
    trigger:
      platform: state
      entity_id: remote.living_room
      to: 'off'
    action:
      - service: remote.turn_off
        entity_id: remote.living_room
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Activity"

#---------------------------------------------------------------------------------------------

